Move the stream writer wrapping up to plugin so it happens as soon as possible.
More concretely, it affects the progress bar as well.

This crashes under Python 3.3:

======================================================================
ERROR: Make sure no unittest frames make it into the traceback.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/erose/Checkouts/nose-progressive/.tox/py33/lib/python3.3/site-packages/nose/plugins/plugintest.py", line 272, in setUp
    self._execPlugin()
  File "/Users/erose/Checkouts/nose-progressive/.tox/py33/lib/python3.3/site-packages/nose/plugins/plugintest.py", line 260, in _execPlugin
    self.output = AccessDecorator(stream)
  File "/Users/erose/Checkouts/nose-progressive/.tox/py33/lib/python3.3/site-packages/nose/plugins/plugintest.py", line 280, in __init__
    stream.seek(0)
  File "/Users/erose/Checkouts/nose-progressive/.tox/py33/lib/python3.3/site-packages/nose/plugins/plugintest.py", line 165, in seek
    self.buffer()
  File "/Users/erose/Checkouts/nose-progressive/.tox/py33/lib/python3.3/site-packages/nose/plugins/plugintest.py", line 150, in buffer
    cache[pid] += data
TypeError: Can't convert 'bytes' object to str implicitly

----------------------------------------------------------------------